-- Create tables11234567aa
CREATE TABLE IF NOT EXISTS `OM_CMN_AccessSeekerContact` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `contactName` varchar(255) DEFAULT NULL,
  `contactPhone` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Application` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `omId` varchar(255) DEFAULT NULL,
  `correlationId` varchar(255) DEFAULT NULL,
  `correlationName` varchar(255) DEFAULT NULL,
  `appianFolderId` int(11) DEFAULT NULL,
  `statusId` int(11) DEFAULT NULL,
  `substatusId` int(11) DEFAULT NULL,
  `locationId` int(11) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `applicationDate` datetime NOT NULL DEFAULT '1970-01-01 00:00:00',
  `expectedCompletionDate` datetime DEFAULT NULL,
  `completionDate` datetime DEFAULT NULL,
  `requestedStartDate` datetime DEFAULT NULL,
  `requestedCompletionDate` datetime DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `applicationOwner` varchar(255) DEFAULT NULL,
  `deleteFlag` tinyint(1) DEFAULT NULL,
  `accessSeekerid` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `OM_CMN_Application_locationId_idx` (`locationId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_ApplicationItem` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `applicationId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `locationId` int(11) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `mainLineItemFlag` tinyint(1) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `completionDate` datetime DEFAULT NULL,
  `expectedCompletionDate` datetime DEFAULT NULL,
  `requestedCompletionDate` datetime DEFAULT NULL,
  `requestedStartDate` datetime DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `OM_CMN_ApplicationItem_applicationId_idx` (`applicationId`) USING BTREE,
  KEY `OM_CMN_ApplicationItem_itemSubTypeRefId_idx` (`itemSubTypeRefId`) USING BTREE,
  KEY `om_cmn_entitytype_om_cmn_applicationitem_fk` (`recordTypeRefId`),
  KEY `om_cmn_location_om_cmn_applicationitem_fk` (`locationId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_APP_ServiceFeasibilityCosting` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `applicationItemId` int(11) NOT NULL,
  `statusId` int(11) DEFAULT NULL,
  `salesforceOppId` varchar(255) DEFAULT NULL,
  `salesforceQuoteName` varchar(255) DEFAULT NULL,
  `salesforceQuoteId` varchar(255) DEFAULT NULL,
  `salesforceParentOppId` varchar(255) DEFAULT NULL,
  `salesforceOppName` varchar(255) DEFAULT NULL,
  `salesforceParentOppName` varchar(255) DEFAULT NULL,
  `ragValue` varchar(255) DEFAULT NULL,
  `fibreBuildCategory` varchar(255) DEFAULT NULL,
  `cost` decimal(13,2) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `bsmApprovalRequired` tinyint(2) DEFAULT NULL,
  `bsmDecision` varchar(255) DEFAULT NULL,
  `estimatedBuildTimeframe` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_app_servicefeasibilitycosting_applicationitemid_idx` (`applicationItemId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Attachment` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `recordTypeRefId` int(11) NOT NULL,
  `entityId` int(11) NOT NULL,
  `attachmentType` varchar(255) NOT NULL,
  `appianDocId` int(11) NOT NULL,
  `attachmentExtension` varchar(255) NOT NULL,
  `attachmentName` varchar(255) NOT NULL,
  `createdBy` varchar(255) NOT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `sortOrder` int(11) DEFAULT NULL,
  `taskName` varchar(255) DEFAULT NULL,
  `docUploadRequired` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_entitytype_om_cmn_attachment_fk` (`recordTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Audit` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `recordTypeRefId` int(11) DEFAULT NULL,
  `recordId` int(11) DEFAULT NULL,
  `actionName` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT NULL,
  `auditTypeRefId` int(11) DEFAULT NULL,
  `assigneeUserOrGroupId` int(11) DEFAULT NULL,
  `taskDeadlineDTime` datetime DEFAULT NULL,
  `taskStartDTime` datetime DEFAULT NULL,
  `buttonAction` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_recordtyperef_om_cmn_audit` (`recordTypeRefId`),
  KEY `om_cmn_r_audittyperef_om_cmn_audit` (`auditTypeRefId`),
  KEY `om_cmn_audit_recordId_idx` (`recordId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_BTD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `btdType` varchar(255) DEFAULT NULL,
  `btdMounting` varchar(255) DEFAULT NULL,
  `powerSupply1` varchar(255) DEFAULT NULL,
  `powerSupply2` varchar(255) DEFAULT NULL,
  `physicalName` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `orderId` int(11) DEFAULT NULL,
  `iesPhysicalInterfaceIpSubnet` varchar(255) DEFAULT NULL,
  `networkPort` varchar(255) DEFAULT NULL,
  `sfpType` varchar(255) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_entitytype_om_cmn_btd_fk` (`recordTypeRefId`),
  KEY `om_cmn_btd_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_CNC` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `nni` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `itemSubTypeRefId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_entitytype_om_cmn_cnc_fk` (`recordTypeRefId`),
  KEY `om_cmn_cnc_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Contact` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `type` varchar(255) NOT NULL,
  `contactName` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `emailAddress` varchar(255) DEFAULT NULL,
  `phoneNumber` varchar(255) DEFAULT NULL,
  `addressLine1` varchar(255) DEFAULT NULL,
  `addressLine2` varchar(255) DEFAULT NULL,
  `addressLine3` varchar(255) DEFAULT NULL,
  `localityName` varchar(255) DEFAULT NULL,
  `businessContactCompany` varchar(255) DEFAULT NULL,
  `postcode` varchar(255) DEFAULT NULL,
  `stateTerritoryCode` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedOn` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_entitytype_om_cmn_contact_fk` (`recordTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Deal` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `dealIdentifier` varchar(255) DEFAULT NULL,
  `RSP` varchar(255) DEFAULT NULL,
  `customer` varchar(255) DEFAULT NULL,
  `dealName` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdBy` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_deal_dealidentifier_idx` (`dealIdentifier`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_EnterpriseEthernet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `billingAccountId` varchar(255) DEFAULT NULL,
  `afterHoursAppointment` varchar(255) DEFAULT NULL,
  `inductionRequired` varchar(255) DEFAULT NULL,
  `securityClearance` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `tradingName` varchar(255) DEFAULT NULL,
  `heritageSite` varchar(255) DEFAULT NULL,
  `term` varchar(255) DEFAULT NULL,
  `serviceRestorationSLA` varchar(255) DEFAULT NULL,
  `accessAvailabilityTarget` varchar(255) DEFAULT NULL,
  `zone` varchar(255) DEFAULT NULL,
  `productType` varchar(255) DEFAULT NULL,
  `templateId` varchar(255) DEFAULT NULL,
  `templateVersion` varchar(255) DEFAULT NULL,
  `npdRequiredFlag` tinyint(1) DEFAULT NULL,
  `orderAcceptedFlag` tinyint(1) DEFAULT NULL,
  `designAssignCompletedFlag` tinyint(4) DEFAULT NULL,
  `csaId` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `orderId` int(11) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `informPlanDesignFlag` tinyint(1) DEFAULT NULL,
  `informDPCommercialFlag` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_enterpriseethernet_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`),
  KEY `om_cmn_enterpriseethernet_itemid_idx` (`itemId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Error` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `recordTypeRefId` int(11) NOT NULL,
  `itemId` int(11) NOT NULL,
  `entityId` int(11) NOT NULL,
  `userMessage` varchar(255) DEFAULT NULL,
  `internalMessage` varchar(2000) DEFAULT NULL,
  `code` varchar(255) DEFAULT NULL,
  `moreInfo` varchar(255) DEFAULT NULL,
  `sourceSystem` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Fibre` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) DEFAULT NULL,
  `dssCableFlag` tinyint(1) DEFAULT NULL,
  `dssCableSize` varchar(255) DEFAULT NULL,
  `noOfTransitionPoints` int(11) DEFAULT NULL,
  `transitionType` varchar(255) DEFAULT NULL,
  `totalRouteDistance` decimal(13,2) DEFAULT NULL,
  `totalHaulingDistance` decimal(13,2) DEFAULT NULL,
  `totalDistanceCivilWorks` decimal(13,2) DEFAULT NULL,
  `fanToCustomerNtdDistance` decimal(13,2) DEFAULT NULL,
  `dssLeadInCableToFan` varchar(255) DEFAULT NULL,
  `ductReservationRequiredFlag` tinyint(1) DEFAULT NULL,
  `estimatedPassiveCosts` decimal(13,2) DEFAULT NULL,
  `fanCode` varchar(255) DEFAULT NULL,
  `aasAvailabilityFlag` tinyint(1) DEFAULT NULL,
  `existingAasSupportServiceFlag` varchar(255) DEFAULT NULL,
  `aasPortAvailabilityFlag` tinyint(1) DEFAULT NULL,
  `transitWorkInvolvedFlag` tinyint(1) DEFAULT NULL,
  `aasServiceStatus` varchar(255) DEFAULT NULL,
  `aasPhysicalName` varchar(255) DEFAULT NULL,
  `aasPhysicalLocation` varchar(255) DEFAULT NULL,
  `portReservationDetails` varchar(255) DEFAULT NULL,
  `reservePortSfpType` varchar(255) DEFAULT NULL,
  `labelOnPortForId` varchar(255) DEFAULT NULL,
  `oltEasBackhaulUpgradeRequiredFlag` tinyint(1) DEFAULT NULL,
  `oltAndPortAvailableFlag` varchar(255) DEFAULT NULL,
  `tsaDesignRefId` varchar(255) DEFAULT NULL,
  `tsaBuildRefId` varchar(255) DEFAULT NULL,
  `estimatedTransitCost` decimal(13,2) DEFAULT NULL,
  `estimatedTransitCompletionDate` date DEFAULT NULL,
  `newOdfRackRequiredFlag` tinyint(1) DEFAULT NULL,
  `newOdfPanelLocations` varchar(255) DEFAULT NULL,
  `insituOdfPanels` varchar(255) DEFAULT NULL,
  `validateReserveActiveNetworkComments` varchar(2000) DEFAULT NULL,
  `dependentProject` varchar(255) DEFAULT NULL,
  `fibreBearer` varchar(255) DEFAULT NULL,
  `circuitBearerId` varchar(255) DEFAULT NULL,
  `aasLogicalName` varchar(255) DEFAULT NULL,
  `aasPort` varchar(255) DEFAULT NULL,
  `aasSfpType` varchar(255) DEFAULT NULL,
  `aasPathDesignComplete` varchar(255) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_fibre_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_FibreJoint` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `fibreJointId` varchar(255) DEFAULT NULL,
  `fibreJointStatus` varchar(255) DEFAULT NULL,
  `fibreJointTypeCode` varchar(255) DEFAULT NULL,
  `fibreJointTypeDescription` varchar(255) DEFAULT NULL,
  `fibreJointLatLong` varchar(255) DEFAULT NULL,
  `loSDistance` decimal(13,2) DEFAULT NULL,
  `revisedDistance` decimal(13,2) DEFAULT NULL,
  `derivedDistance` decimal(13,2) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `OM_CMN_FibreJoint_itemId_idx` (`itemId`) USING BTREE,
  KEY `om_cmn_entitytype_om_cmn_fibrejoint_fk` (`recordTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_LinkedOrder` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `parentOrderId` int(11) NOT NULL,
  `childOrderId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_linkedorder_om_cmn_order_parent_fk` (`parentOrderId`),
  KEY `om_cmn_linkedorder_om_cmn_order_child_fk` (`childOrderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Location` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `locationType` varchar(255) DEFAULT NULL,
  `locId` varchar(255) NOT NULL,
  `longitude` varchar(255) DEFAULT NULL,
  `latitude` varchar(255) DEFAULT NULL,
  `primaryTechnology` varchar(255) DEFAULT NULL,
  `accessTechnologyType` varchar(255) DEFAULT NULL,
  `fsaId` varchar(255) DEFAULT NULL,
  `csaId` varchar(255) DEFAULT NULL,
  `samId` varchar(255) DEFAULT NULL,
  `addressFullText` varchar(255) DEFAULT NULL,
  `levelType` varchar(255) DEFAULT NULL,
  `levelNumber` varchar(255) DEFAULT NULL,
  `unitType` varchar(255) DEFAULT NULL,
  `unitNumber` varchar(255) DEFAULT NULL,
  `roadNumber1` varchar(255) DEFAULT NULL,
  `roadNumber2` varchar(255) DEFAULT NULL,
  `roadName` varchar(255) DEFAULT NULL,
  `roadTypeCode` varchar(255) DEFAULT NULL,
  `locality` varchar(255) DEFAULT NULL,
  `postcode` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `serviceRegion` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `serviceType` varchar(255) DEFAULT NULL,
  `streetName` varchar(255) DEFAULT NULL,
  `streetType` varchar(255) DEFAULT NULL,
  `street` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_location_state_idx` (`state`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Lock` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entityTypeId` int(11) DEFAULT NULL,
  `uniqueId` varchar(255) DEFAULT NULL,
  `entityId` int(11) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uniqueId` (`uniqueId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Milestone` (
  `id` int(11) NOT NULL COMMENT 'Primary Key',
  `recordTypeRefId` int(11) DEFAULT NULL COMMENT 'FK with Record Type reference',
  `entityId` int(11) DEFAULT NULL COMMENT 'Entity Id of the Entity Type',
  `activityCode` varchar(55) DEFAULT NULL COMMENT 'Activity Code for P6',
  `activityName` varchar(255) DEFAULT NULL COMMENT 'Activity Name for P6',
  `projectManagerUserName` varchar(55) DEFAULT NULL COMMENT 'User name of Project Manager',
  `projectManagerName` varchar(100) DEFAULT NULL COMMENT 'Project Manager name',
  `baselineStart` date DEFAULT NULL COMMENT 'Baseline Start Date',
  `baselineFinish` date DEFAULT NULL COMMENT 'Baseline Finish Date',
  `forecastStart` date DEFAULT NULL COMMENT 'Forecast Start Date',
  `forecastFinish` date DEFAULT NULL COMMENT 'Forecast Finish Date',
  `actualStart` date DEFAULT NULL COMMENT 'Actual Start Date',
  `actualFinish` date DEFAULT NULL COMMENT 'Actual Finish Date',
  `actualised` varchar(10) DEFAULT NULL COMMENT 'Actualised',
  `createdBy` varchar(50) DEFAULT NULL COMMENT 'Created By',
  `createdOn` datetime DEFAULT NULL COMMENT 'Created On',
  `updatedBy` varchar(50) DEFAULT NULL COMMENT 'Updated By',
  `updatedOn` datetime DEFAULT NULL COMMENT 'Updated On',
  `isActive` tinyint(1) DEFAULT NULL COMMENT 'Is Active or Not',
  PRIMARY KEY (`id`),
  KEY `om_cmn_milestone_entityid_idx` (`entityId`),
  KEY `om_cmn_milestone_recordtyperefid_idx` (`recordTypeRefId`),
  KEY `om_cmn_milestone_isactive_idx` (`isActive`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This table holds the Milestone for the Respective AYCA ID';

CREATE TABLE IF NOT EXISTS `OM_CMN_NBNSelect` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `afterHoursSiteVisit` varchar(255) DEFAULT NULL,
  `inductionRequired` varchar(255) DEFAULT NULL,
  `securityRequirements` varchar(500) DEFAULT NULL,
  `billingAccountID` varchar(255) DEFAULT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `additionalNotes` varchar(1000) DEFAULT NULL,
  `tradingName` varchar(255) DEFAULT NULL,
  `heritageSite` varchar(255) DEFAULT NULL,
  `siteName` varchar(255) DEFAULT NULL,
  `ownerAwareOfProposal` varchar(255) DEFAULT NULL,
  `siteAccessInstructions` varchar(500) DEFAULT NULL,
  `siteType` varchar(255) DEFAULT NULL,
  `resourceOrderType` varchar(255) DEFAULT NULL,
  `propertyOwnershipStatus` varchar(255) DEFAULT NULL,
  `keysRequired` varchar(255) DEFAULT NULL,
  `contractedLocationInstructions` varchar(500) DEFAULT NULL,
  `orderAcceptedFlag` tinyint(4) DEFAULT NULL,
  `safetyHazards` varchar(255) DEFAULT NULL,
  `jsasswmRequired` varchar(255) DEFAULT NULL,
  `workPracticesRequired` varchar(255) DEFAULT NULL,
  `workingAtHeightsConsideration` varchar(255) DEFAULT NULL,
  `confinedSpaceRequirements` varchar(255) DEFAULT NULL,
  `numberOfServices` varchar(255) DEFAULT NULL,
  `isComplexSite` varchar(255) DEFAULT NULL,
  `internalPCDRequired` varchar(255) DEFAULT NULL,
  `siteEquipmentOtherInfo` varchar(255) DEFAULT NULL,
  `specialRequirementOther` varchar(500) DEFAULT NULL,
  `detailedPLASEAssessment` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdondtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedondtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_nbnselect_itemid_idx` (`itemId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Note` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entityId` int(11) DEFAULT NULL,
  `recordTypeRefId` int(11) DEFAULT NULL,
  `taskName` varchar(255) DEFAULT NULL,
  `note` varchar(5000) DEFAULT NULL,
  `addedBy` varchar(255) DEFAULT NULL,
  `addedOnDTime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_NPDConstruct` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) DEFAULT NULL,
  `opticalResults` varchar(255) DEFAULT NULL,
  `isNetworkBuiltAndNoOutages` tinyint(4) DEFAULT NULL,
  `submitCompletionFlag` tinyint(4) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_npdconstruct_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_NPDDesign` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) DEFAULT NULL,
  `ffsMandRequiredFlag` tinyint(4) DEFAULT NULL,
  `ffsNonMandRequiredFlag` tinyint(4) DEFAULT NULL,
  `ffsMandatoryCost` decimal(13,2) DEFAULT NULL,
  `ffsNonMandatoryCost` decimal(13,2) DEFAULT NULL,
  `isTLSRespReceived` tinyint(4) DEFAULT NULL,
  `isBTDDesignComplete` tinyint(4) DEFAULT NULL,
  `submittedToTelstraFlag_10_1_2` varchar(255) DEFAULT NULL,
  `submittedToTelstraFlag_10_1_3` varchar(255) DEFAULT NULL,
  `partAResponseFlag` varchar(255) DEFAULT NULL,
  `partBResponseFlag` varchar(255) DEFAULT NULL,
  `isFinNoticeBoundaryEmailedToTls` tinyint(4) DEFAULT NULL,
  `isOption3TLSRespReceived` tinyint(4) DEFAULT NULL,
  `isDuctReservationGMLApproved_10_1_1` tinyint(4) DEFAULT NULL,
  `isFFSConfirm` tinyint(4) DEFAULT NULL,
  `reviewDesignApprovedFlag` tinyint(4) DEFAULT NULL,
  `financeCode` varchar(255) DEFAULT NULL,
  `macsMrq` varchar(255) DEFAULT NULL,
  `activeNetworkP6ProjectId` varchar(255) DEFAULT NULL,
  `laseTeamFeedbackFlag` varchar(255) DEFAULT NULL,
  `expectedCompletionDate` date DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `mrqId` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_npddesign_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`),
  KEY `om_cmn_npddesign_itemid_idx` (`itemId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_NPDPlan` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `npdApplicationId` int(11) DEFAULT NULL,
  `npdApplicationName` varchar(255) DEFAULT NULL,
  `itemId` int(11) DEFAULT NULL,
  `scopeOfWorkForDeliveryPartner` varchar(255) DEFAULT NULL,
  `stateDeliveryRegion` varchar(255) DEFAULT NULL,
  `deliveryPartner` varchar(255) DEFAULT NULL,
  `projectCode` varchar(255) DEFAULT NULL,
  `transitBuildType` varchar(255) DEFAULT NULL,
  `orderCategory` varchar(255) DEFAULT NULL,
  `lowerRangeDays` int(11) DEFAULT NULL,
  `upperRangeDays` int(11) DEFAULT NULL,
  `timeVarianceFlag` tinyint(1) DEFAULT NULL,
  `estimatedPassiveCost` decimal(13,2) DEFAULT NULL,
  `thresholdCost` decimal(13,2) DEFAULT NULL,
  `costVariance` decimal(13,2) DEFAULT NULL,
  `fbcDelta` decimal(13,2) DEFAULT NULL,
  `absorbFbcDelta` varchar(255) DEFAULT NULL,
  `agreedRspFbcDelta` decimal(13,2) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `finalFbc` decimal(13,2) DEFAULT NULL,
  `buildComplexity` varchar(255) DEFAULT NULL COMMENT 'Build Complexity assessed by PDP team',
  PRIMARY KEY (`id`),
  KEY `om_cmn_npdplan_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_NS_NPDConstruct` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) DEFAULT NULL,
  `constructCommencementDate` datetime DEFAULT NULL,
  `pniUpdateDate` datetime DEFAULT NULL,
  `ntdInstalledDate` datetime DEFAULT NULL,
  `rdCalledToNotifyVisTest` tinyint(4) DEFAULT NULL,
  `FODBoundaryExists` tinyint(4) DEFAULT NULL,
  `testCompletionDate` datetime DEFAULT NULL,
  `committedDeliveryDate` datetime DEFAULT NULL,
  `networkTraceCompletionDate` datetime DEFAULT NULL,
  `accessTechnologyCompletionDate` datetime DEFAULT NULL,
  `submitCompletionFlag` tinyint(4) DEFAULT NULL,
  `createdDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedDtime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `transitionReportExportedBy` varchar(255) DEFAULT NULL,
  `transitionExportedDate` datetime DEFAULT NULL,
  `completionArtefactsApproved` tinyint(4) DEFAULT NULL,
  `bomboqApproved` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_NS_NPDPlanDesign` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) DEFAULT NULL,
  `buildCategory` varchar(255) DEFAULT NULL,
  `avrRequired` tinyint(4) DEFAULT NULL,
  `workReleaseScheduled` tinyint(4) DEFAULT NULL,
  `deliveryPartner` varchar(255) DEFAULT NULL,
  `isPONPatchingRequired` tinyint(4) DEFAULT NULL,
  `buildCategoryChange` tinyint(4) DEFAULT NULL,
  `revisedBuildCategory` varchar(255) DEFAULT NULL,
  `costVariance` tinyint(4) DEFAULT NULL,
  `signedOffBy` varchar(255) DEFAULT NULL,
  `approvedOrRejectDate` datetime DEFAULT NULL,
  `isTLSRequired` tinyint(4) DEFAULT NULL,
  `tlsSubmitDate` datetime DEFAULT NULL,
  `designOutcome` varchar(255) DEFAULT NULL,
  `tlsApprovedDate` datetime DEFAULT NULL,
  `proceedToConstruction` tinyint(4) DEFAULT NULL,
  `createdDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedDtime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `isDesignRejectedAnyTime` tinyint(4) DEFAULT NULL,
  `isFODBoundaryCreated` tinyint(4) DEFAULT NULL COMMENT 'From now on (MR1905) FOD is referred as OVB.',
  `buildCategoryWorkRelease` varchar(255) DEFAULT NULL COMMENT 'Build Category value captured at Issue work release task',
  `resolveDDDBuildCategory` varchar(255) DEFAULT NULL COMMENT 'Build Category value captured at resolve F-DDD task',
  `isRSPActionedAnyTime` tinyint(1) DEFAULT NULL COMMENT 'To know whether RSP Actioned any time in NPD Lifecycle',
  `tShirtClassificationFeasibility` varchar(255) DEFAULT NULL,
  `buildComplexity` varchar(255) DEFAULT NULL,
  `buildComplexityPlanDesign` varchar(255) DEFAULT NULL COMMENT 'Build Complexity value updated by PlanDesign team',
  `buildComplexityPlanDesignMgnt` varchar(255) DEFAULT NULL COMMENT 'Build Complexity value updated by PlanDesign Manager',
  `plannedPlanCommenceDate` datetime DEFAULT NULL,
  `plannedPlanCompletionDate` datetime DEFAULT NULL,
  `deliveryPartnerPDP` varchar(255) DEFAULT NULL,
  `financeCode` varchar(255) DEFAULT NULL,
  `newBuildCost` decimal(10,2) DEFAULT NULL,
  `costVarianceActionRequired` varchar(255) DEFAULT NULL,
  `macsMrq` varchar(255) DEFAULT NULL,
  `purchaseOrderId` varchar(255) DEFAULT NULL,
  `workReleaseId` varchar(255) DEFAULT NULL,
  `designVersionNumber` varchar(255) DEFAULT NULL,
  `bomboqVersionNumber` varchar(255) DEFAULT NULL,
  `isBuildCategoryChangeAcknowledged` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_ns_npdplandesign_itemid_idx` (`itemId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_NTD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `type` varchar(255) DEFAULT NULL,
  `batteryBackupRequired` varchar(255) DEFAULT NULL,
  `createdby` varchar(255) DEFAULT NULL,
  `createdondtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedby` varchar(255) DEFAULT NULL,
  `updatedondtime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ntdInstallAppointmentDate` datetime DEFAULT NULL,
  `ntdPowerType` varchar(255) DEFAULT NULL,
  `ntdSerial` varchar(255) DEFAULT NULL,
  `PSUSerialNumber` varchar(255) DEFAULT NULL,
  `ntdInstallAppointmentDTime_txt` varchar(255) DEFAULT NULL,
  `testedUsingTemporaryPower` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `omId` varchar(255) DEFAULT NULL,
  `correlationId` varchar(255) DEFAULT NULL,
  `correlationName` varchar(255) DEFAULT NULL,
  `appianFolderId` int(11) DEFAULT NULL,
  `statusId` int(11) DEFAULT NULL,
  `substatusId` int(11) DEFAULT NULL,
  `locationId` int(11) DEFAULT NULL,
  `orderTypeRefId` int(11) NOT NULL,
  `state` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `orderDate` datetime NOT NULL DEFAULT '1970-12-31 00:00:00' COMMENT 'date order received in om',
  `expectedCompletionDate` datetime DEFAULT NULL,
  `completionDate` datetime DEFAULT NULL,
  `requestedStartDate` datetime DEFAULT NULL,
  `requestedCompletionDate` datetime DEFAULT NULL,
  `updatedBy` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `productHeaderId` int(11) DEFAULT NULL,
  `priId` varchar(255) DEFAULT NULL,
  `orderType` varchar(255) DEFAULT NULL,
  `orderSubType` varchar(255) DEFAULT NULL COMMENT 'defines subType of an order as Product/Resource/Service',
  `applicationId` int(11) DEFAULT NULL,
  `accessSeekerContactId` int(11) DEFAULT NULL,
  `accessSeekerId` varchar(255) DEFAULT NULL,
  `pendFlag` tinyint(1) DEFAULT NULL,
  `opoAppianDocId` int(11) DEFAULT NULL,
  `npdStatusId` int(11) DEFAULT NULL,
  `npdSubstatusId` int(11) DEFAULT NULL,
  `sendNotificationsFlag` tinyint(1) DEFAULT NULL,
  `finalStatusCompletedFlag` tinyint(1) DEFAULT NULL,
  `parentOrderId` int(11) DEFAULT NULL,
  `subprocessPendFlag` tinyint(1) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `opo` json DEFAULT NULL COMMENT 'stores the original product order json body note that this is not in the Appian CDT as we only use this in a stored proc and Appian doesn''t support the JSON data type.',
  `deleteFlag` tinyint(1) DEFAULT NULL,
  `statusVersionId` int(11) NOT NULL COMMENT 'allows versioning of the e2e status and substatus values',
  `itemSubTypeRefId` int(11) NOT NULL,
  `USRN` varchar(255) DEFAULT NULL,
  `channel` varchar(255) DEFAULT NULL,
  `dealId` int(11) DEFAULT NULL,
  `shortfallType` varchar(255) DEFAULT NULL,
  `acknowledgedDate` datetime DEFAULT NULL COMMENT 'date order acknowledged in om',
  `falloutFlag` tinyint(1) DEFAULT '0' COMMENT 'marked as T if this order is currently in fallout - this value remains until the shortfall is fixed',
  `nbnURN` varchar(255) DEFAULT NULL,
  `CRMCaseNumber` varchar(255) DEFAULT NULL,
  `readyToConnectDate` datetime DEFAULT NULL,
  `originalSuppliedAddress` varchar(255) DEFAULT NULL,
  `tranche` varchar(255) DEFAULT NULL,
  `sitePriority` varchar(255) DEFAULT NULL,
  `custPendFlag` tinyint(1) DEFAULT '0' COMMENT 'used when a nbn internal user pends the order to track all customer caused delays',
  `afterHoursProcessing` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `locationId_idx` (`locationId`),
  KEY `applicationId_idx` (`applicationId`),
  KEY `om_cmn_accessseekercontact_om_cmn_order_fk` (`accessSeekerContactId`),
  KEY `om_cmn_productheader_om_cmn_order_fk` (`productHeaderId`),
  KEY `om_cmn_r_ordertype_om_cmn_order` (`orderTypeRefId`),
  KEY `om_cmn_r_statusversionref_om_cmn_order` (`statusVersionId`),
  KEY `om_cmn_r_itemsubtyperef_om_cmn_order` (`itemSubTypeRefId`),
  KEY `om_cmn_r_statusref_om_cmn_order_fk` (`statusId`),
  KEY `om_cmn_r_substatusref_om_cmn_order_fk` (`substatusId`),
  KEY `om_cmn_deal_om_cmn_order_fk` (`dealId`),
  KEY `om_cmn_order_omid_idx` (`omId`),
  KEY `om_cmn_r_lookupref_om_cmn_order_fk` (`afterHoursProcessing`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_OrderContactLink` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderItemId` int(11) NOT NULL,
  `contactId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_ordercontactlink_orderitemId_idx` (`orderItemId`),
  KEY `om_cmn_ordercontactlink_contactId_idx` (`contactId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Allows a contact to be shared with multiple order items';

CREATE TABLE IF NOT EXISTS `OM_CMN_OrderItem` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` int(11) DEFAULT NULL,
  `itemTypeRefId` int(11) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `locationId` int(11) DEFAULT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `idx` int(11) NOT NULL COMMENT 'temp index given when inserting from json for each itemtype',
  `parentOrderItemId` int(11) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `mainLineItemFlag` tinyint(1) NOT NULL,
  `action` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `completionDate` datetime DEFAULT NULL,
  `expectedCompletionDate` datetime DEFAULT NULL,
  `requestedCompletionDate` datetime DEFAULT NULL,
  `requestedStartDate` datetime DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `hideSummaryRowFlag` tinyint(1) DEFAULT NULL,
  `entityId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `OM_CMN_OrderItem_orderId_idx` (`orderId`) USING BTREE,
  KEY `om_cmn_entitytype_om_cmn_orderitem_fk` (`recordTypeRefId`),
  KEY `om_cmn_location_om_cmn_orderitem_fk` (`locationId`),
  KEY `om_cmn_r_itemsubtyperef_om_cmn_orderitem_fk` (`itemSubTypeRefId`),
  KEY `om_cmn_orderitem_entityid_idx` (`entityId`) USING BTREE,
  KEY `om_cmn_r_itemtype_om_cmn_orderitem_fk` (`itemTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_OrderItemLink` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderItemId` int(11) NOT NULL,
  `itemSubTypeRefId` int(11) DEFAULT NULL,
  `entityId` int(11) NOT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `OM_CMN_OrderItemLink_orderitemId_idx` (`orderItemId`) USING BTREE,
  KEY `OM_CMN_OrderItemLink_entityid_idx` (`entityId`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This allows an entity to be reused against multiple orderItems\r\nFor instance, a Product Order (ORD) will contain all of the resources and services against it, then if a Resource Order (ROR) is created against the ORD, then we will relate all of the same resources and services as well (if required).';

CREATE TABLE IF NOT EXISTS `OM_CMN_OrderSecurity` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` int(11) NOT NULL,
  `username` varchar(255) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_order_om_cmn_ordersecurity_fk` (`orderId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='allows record level security across orders';

CREATE TABLE IF NOT EXISTS `OM_CMN_OVC` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `uniId` int(11) DEFAULT NULL,
  `itemId` int(11) DEFAULT NULL,
  `idx` int(11) NOT NULL COMMENT 'temp index given when inserting from json',
  `recordTypeRefId` int(11) NOT NULL,
  `poi` varchar(255) DEFAULT NULL,
  `nni` varchar(255) DEFAULT NULL,
  `routeType` varchar(255) DEFAULT NULL,
  `sVLanId` varchar(255) DEFAULT NULL,
  `maximumFrameSize` varchar(255) DEFAULT NULL,
  `cosHighBandwidth` varchar(255) DEFAULT NULL,
  `cosMediumBandwidth` varchar(255) DEFAULT NULL,
  `cosLowBandwidth` varchar(255) DEFAULT NULL,
  `uniVLanId` varchar(255) DEFAULT NULL,
  `connectedTo` varchar(255) DEFAULT NULL,
  `enniLagId` varchar(255) DEFAULT NULL,
  `ovcTransientId` varchar(255) DEFAULT NULL,
  `cncId` int(11) DEFAULT NULL,
  `cosMappingMode` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `samInstanceId` varchar(255) DEFAULT NULL,
  `orderId` int(11) DEFAULT NULL,
  `ovcConfiguredFlag` tinyint(1) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_ovc_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`),
  KEY `om_cmn_uni_om_cmn_ovc_fk` (`uniId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Preference` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `username` varchar(255) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `preference` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_ProcessDecision` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` int(11) DEFAULT NULL,
  `processDecisionRefId` int(11) DEFAULT NULL,
  `decisionFlag` tinyint(1) DEFAULT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `unique_index` (`orderId`,`name`),
  KEY `om_cmn_r_processdecisionref_om_cmn_processdecision_fk` (`processDecisionRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_ProductHeader` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `activityName` varchar(255) DEFAULT NULL,
  `msgName` varchar(255) DEFAULT NULL,
  `businessServiceName` varchar(255) DEFAULT NULL,
  `businessProcessVersion` varchar(255) DEFAULT NULL,
  `businessServiceVersion` varchar(255) DEFAULT NULL,
  `msgType` varchar(255) DEFAULT NULL,
  `security` varchar(255) DEFAULT NULL,
  `communicationPattern` varchar(255) DEFAULT NULL,
  `orderPriority` varchar(255) DEFAULT NULL,
  `timestamp` datetime DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `createdBy` varchar(255) NOT NULL DEFAULT 'COM System',
  `businessChannel` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_R_AuditTypeRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_R_Index` (
  `idx` int(11) NOT NULL,
  `idxRef` int(11) DEFAULT NULL,
  PRIMARY KEY (`idx`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='reference table for joins inside stored procs which extract json data - no physical table joins';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_ItemSubTypeRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `itemTypeRefId` int(11) NOT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_itemtyperef_om_cmn_r_itemsubtyperef_fk` (`itemTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Defines the type of entity that this orderItem represents. Current values: Enterprise Ethernet (to describe an orderItem as an EE product), BTD, UNI, OVC';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_ItemTypeRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_R_LocationPostCode` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `postcode` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Contains the postcodes for Service Level Region (SLR) Check';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_LookupRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(255) DEFAULT NULL COMMENT 'Known categories: Attachment Type, Attachment Extension, EE NPD Design Task, EE NPD Scope of Work',
  `label` varchar(255) NOT NULL,
  `value` varchar(255) NOT NULL,
  `sortOrder` int(11) DEFAULT NULL COMMENT 'allows sequential ordering for each category',
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='A generic table of simple label/value pair relationships by type that can be stored in one table instead of bespoke for each type of list';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_OrderTypeRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='either a product order (ORD) or resource order (ROR)';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_ProcessDecisionRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemSubTypeRefId` int(11) NOT NULL,
  `name` varchar(255) NOT NULL,
  `defaultValue` tinyint(1) NOT NULL DEFAULT '0',
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_processdecisionref_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Creates a set of configurable COM/ROM routing based on the product - each new Order will create a set of these into the OM_CMN_ProcessDecision transaction table. there is no FK ref back to this ref table, as it is just a direct copy, so that the ref table is decoupled from the template';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_RecordTypeRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_R_ServiceType` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) DEFAULT NULL,
  `auditMessage` varchar(255) DEFAULT NULL COMMENT 'the message used to write into the audit table - without the "action", this will be concatenated depending on if it was successful, for instance D&A Completed or D&A Fallout should only capture D&A against auditMessage',
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_R_StatusRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `statusTypeRef` varchar(255) DEFAULT NULL COMMENT 'currently only set to either ORD, ROR, NPD\r\nmake a decision to not normalise this data',
  `name` varchar(255) NOT NULL,
  `sortOrder` int(11) NOT NULL DEFAULT '0' COMMENT 'allows sequential ordering for milestone type views',
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedBy` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='All top level status values for Applications and Orders';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_StatusVersionLinkRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `statusVersionRefId` int(11) NOT NULL,
  `substatusRefId` int(11) NOT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_statusversionref_om_cmn_r_statustemplateref_fk` (`statusVersionRefId`),
  KEY `om_cmn_r_substatusref_om_cmn_r_statustemplateref_fk` (`substatusRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='contains a list of all statuses that an order moves through, linked to a known versionthis ensbles reuse of a generic set of status/substatus values irrespective of order or product type';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_StatusVersionRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `productId` int(11) DEFAULT NULL COMMENT 'needs to ref the OM_CMN_R_ItemSubTypeRef product value',
  `orderTypeRefId` int(11) NOT NULL COMMENT 'COM or ROM order',
  `versionNo` int(11) NOT NULL COMMENT 'each new order will find the highest matching version for a given productId, mpoOrderType and orderTypeRefId',
  `name` varchar(255) NOT NULL COMMENT 'used to describe the version, not used in lookups',
  `mpoOrderType` varchar(255) DEFAULT NULL COMMENT 'Connect or Modify\r\nshould change to a lookup table value refId',
  `isActiveFlag` tinyint(1) NOT NULL DEFAULT '1',
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `shortfallType` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_statusversionref_om_cmn_r_ordertyperef` (`orderTypeRefId`),
  KEY `om_cmn_r_statusversionref_om_cmn_r_itemsubtyperef` (`productId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='tracks versions of statuses for different products in OM';

CREATE TABLE IF NOT EXISTS `OM_CMN_R_SubstatusRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `statusRefId` int(11) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `sortOrder` int(11) NOT NULL DEFAULT '0' COMMENT 'allows sequential ordering for milestone type views',
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedBy` varchar(255) DEFAULT NULL,
  `isActiveFlag` tinyint(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_statusref_om_cmn_r_substatusref_fk` (`statusRefId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='All sub status values for Applications and Orders';

CREATE TABLE IF NOT EXISTS `OM_CMN_ServiceLog` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `startTime` datetime DEFAULT NULL,
  `endTime` datetime DEFAULT NULL,
  `errorOccurred` tinyint(1) DEFAULT NULL,
  `requestObject` varchar(5000) DEFAULT NULL,
  `responseObject` varchar(5000) DEFAULT NULL,
  `correlationId` varchar(255) DEFAULT NULL,
  `serviceTypeId` int(11) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOn` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `retryCount` int(11) DEFAULT NULL,
  `appianProcessId` int(11) DEFAULT NULL,
  `entityId` int(11) DEFAULT NULL COMMENT 'for orders, this is the orderId',
  `productType` varchar(255) DEFAULT NULL,
  `requestId` char(36) DEFAULT NULL COMMENT 'UUID which allows Appian to retry a request in the event of a fallout',
  `updatedOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `requestJson` json DEFAULT NULL,
  `responseJson` json DEFAULT NULL,
  `notificationType` varchar(255) NOT NULL COMMENT 'used when retrying the request to pass into a process model param',
  `processName` varchar(255) NOT NULL COMMENT 'used when retrying the request to pass into a process model param',
  `testCaseFlag` tinyint(1) NOT NULL DEFAULT '0' COMMENT 'allows automated and manual test cases to be executed and separated from real process entries',
  PRIMARY KEY (`id`),
  KEY `om_cmn_r_servicetyperef_om_cmn_servicelog_fk` (`serviceTypeId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Site` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `cncId` int(11) NOT NULL,
  `hostName` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_entitytype_om_cmn_site_fk` (`cncId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_AccessSeekerContact` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `processId` int(11) DEFAULT NULL,
  `contactName` varchar(255) DEFAULT NULL,
  `contactPhone` varchar(255) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_BSSite` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `processId` int(11) NOT NULL COMMENT 'valid processId, should not be null',
  `dealName` varchar(255) DEFAULT NULL COMMENT 'valid dealName with Free text',
  `USRN` varchar(255) DEFAULT NULL COMMENT 'unique aycaId char type',
  `locId` varchar(255) DEFAULT NULL COMMENT 'valid locId with char type',
  `state` varchar(255) DEFAULT NULL COMMENT 'valid state with type alphabetic',
  `postcode` varchar(255) DEFAULT NULL COMMENT 'valid postcode with numeric type',
  `localityName` varchar(255) DEFAULT NULL COMMENT 'valid localityName with char type',
  `streetName` varchar(255) DEFAULT NULL COMMENT 'valid streetName with char type',
  `streetType` varchar(255) DEFAULT NULL COMMENT 'valid streetType with char type',
  `street` varchar(255) DEFAULT NULL COMMENT 'valid street with aphanumeric type',
  `propertyType` varchar(255) DEFAULT NULL COMMENT 'valid propertyType with valid char type',
  `propertyNumber` varchar(255) DEFAULT NULL COMMENT 'valid propertyNumber  with valid numeric type',
  `lattitude` varchar(255) DEFAULT NULL COMMENT 'valid lattitude',
  `longitude` varchar(255) DEFAULT NULL COMMENT 'valid longitude',
  `siteName` varchar(255) DEFAULT NULL COMMENT 'valid siteName with char type',
  `siteType` varchar(255) DEFAULT NULL COMMENT 'valid siteType with char type',
  `heritageSite` varchar(255) DEFAULT NULL COMMENT 'valid heritageSite with char type',
  `tradingName` varchar(255) DEFAULT NULL COMMENT 'valid tradingName with char type',
  `propertyOwnershipStatus` varchar(255) DEFAULT NULL COMMENT 'valid propertyOwnershipStatus with char type',
  `keysRequired` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, unsure',
  `securityRequirements` text,
  `siteAccessInstructions` text,
  `contractedLocationInstructions` text,
  `ownerAwareOfProposal` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No',
  `inductionRequired` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, Unsure',
  `safetyHazards` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No',
  `afterHoursSiteVisit` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, Unsure',
  `jsaswmRequired` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, Unsure',
  `workPracticesRequired` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, unsure',
  `workingAtHeightsConsideration` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, unsure',
  `additionalNotes` text,
  `confinedSpaceRequirements` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes,No, unsure',
  `businessContactFirstName` varchar(255) DEFAULT NULL COMMENT 'Varchar type',
  `businessContactSurname` varchar(255) DEFAULT NULL COMMENT 'Varchar type',
  `businessContactContactEmail` varchar(255) DEFAULT NULL COMMENT 'valid email address',
  `businessContactContactNumber` varchar(255) DEFAULT NULL COMMENT 'valid contact number',
  `businessContactCompany` varchar(255) DEFAULT NULL COMMENT 'valid company name',
  `businessContactRole` varchar(255) DEFAULT NULL COMMENT 'valid role',
  `businessContactStreetAddress` varchar(255) DEFAULT NULL COMMENT 'valid street address',
  `businessContactSuburb` varchar(255) DEFAULT NULL COMMENT 'valid subrub',
  `businessContactState` varchar(255) DEFAULT NULL COMMENT 'valid state',
  `businessContactPostcode` varchar(255) DEFAULT NULL COMMENT 'valid postcode',
  `siteContactFirstName` varchar(255) DEFAULT NULL COMMENT 'valid site first name',
  `siteContactSurname` varchar(255) DEFAULT NULL COMMENT 'valid site surname',
  `siteContactContactEmail` varchar(255) DEFAULT NULL COMMENT 'valid site email',
  `siteContactContactNumber` varchar(255) DEFAULT NULL COMMENT 'valid site email',
  `secondarySiteContactFirstName` varchar(255) DEFAULT NULL,
  `secondarySiteContactSurname` varchar(255) DEFAULT NULL,
  `secondarySiteContactContactEmail` varchar(255) DEFAULT NULL,
  `secondarySiteContactContactNumber` varchar(255) DEFAULT NULL,
  `customerRequiredDate` varchar(255) DEFAULT NULL,
  `notes` text,
  `batteryBackupRequired` varchar(255) DEFAULT NULL COMMENT 'valid values are Yes, No, Unsure',
  `accessSeekerInteractionBillingAccountID` varchar(255) DEFAULT NULL COMMENT 'valid accessSeekerInteractionBillingAccountID',
  `accessSeekerContactContactName` varchar(255) DEFAULT NULL COMMENT 'valid accessSeekerContactContactName',
  `accessSeekerContactContactPhone` varchar(255) DEFAULT NULL COMMENT 'valid accessSeekerContactContactPhone',
  `productType` varchar(255) DEFAULT NULL COMMENT 'valid value is NBNSelect',
  `orderType` varchar(255) DEFAULT NULL COMMENT 'valid value is CONNECT',
  `errorDetails` varchar(2000) DEFAULT NULL COMMENT 'error details',
  `isCommenced` tinyint(1) DEFAULT NULL,
  `OmID` text,
  `RSP` text,
  `deliveryPartner` text,
  `nbnURN` text,
  `CRMCaseNumber` text,
  `samId` text,
  `originalAddress` text,
  `tranche` text,
  `sitePriority` text,
  `TShirtClassificationFeasibility` text,
  `category` text,
  `plannedPlanCommenceDate` varchar(255) DEFAULT NULL,
  `plannedPlanCompleteDate` varchar(255) DEFAULT NULL,
  `readyToConnectDate` varchar(255) DEFAULT NULL,
  `numberOfServices` text,
  `financeCode` text,
  `PLASEdetailedAssessment` text,
  `buildingMgntContactName` text,
  `buildingMgntContactPhone` text,
  `buildingMgntContactEmail` text,
  `buildingOwnerContactName` text,
  `buildingOwnerContactPhone` text,
  `buildingOwnerContactEmail` text,
  `clientHSEMgrContactName` text,
  `clientHSEMgrContactPhone` text,
  `clientHSEMgrContactEmail` text,
  `isComplexSite` text,
  `internalPCDRequired` text,
  `siteEquipmentOtherInfo` text,
  `specialRequirementOther` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table holds for the Staging information of the Sites list for Manual Upload';

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_BTD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx` int(11) DEFAULT NULL COMMENT '	represents the zero based index of the item from the original jdoc',
  `action` varchar(255) DEFAULT NULL COMMENT 'will ultimately be saved against the OrderItem',
  `btdType` varchar(255) DEFAULT NULL,
  `btdMounting` varchar(255) DEFAULT NULL,
  `powerSupply1` varchar(255) DEFAULT NULL,
  `powerSupply2` varchar(255) DEFAULT NULL,
  `physicalName` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `orderItemId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_CNC` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `action` varchar(255) DEFAULT NULL COMMENT 'will ultimately be saved against the OrderItem',
  `recordTypeRefId` int(11) DEFAULT NULL,
  `nni` varchar(255) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `orderItemId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_CommercialFinance` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key for this Staging table',
  `account` varchar(255) DEFAULT NULL COMMENT 'Holds the Deal Name or the Trading order based on Deal based or not',
  `identifier` varchar(255) DEFAULT NULL COMMENT 'Holds the Identifier for Single sties which is ROR ID and for Deal based it is Dead ID',
  `samId` varchar(50) DEFAULT NULL COMMENT 'SAM ID which is related to the Site',
  `state` varchar(50) DEFAULT NULL COMMENT 'Contains the State for the related Site or Order',
  `productType` varchar(50) DEFAULT NULL COMMENT 'Holds the Product Type of the Site/Order',
  `orderChannel` varchar(50) DEFAULT NULL COMMENT 'Contains the Channel or Order placed into the System',
  `oracleProjectNumber` varchar(255) DEFAULT NULL COMMENT 'Contains the Finance Code/Project Code from Oracle as a Response',
  `errorCode` tinyint(1) DEFAULT NULL COMMENT 'Error Code for the imported data',
  `errorMessage` varchar(3000) DEFAULT NULL COMMENT 'Error text for the imported data',
  `processId` int(11) DEFAULT NULL COMMENT 'Process Id from Appian',
  `createdBy` varchar(50) DEFAULT NULL COMMENT 'User who initiated the process',
  `createdOn` datetime DEFAULT NULL COMMENT 'Date and Time when it is been imported',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Staging Table for Commercial Finance Code import function';

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_Contact` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx` int(11) DEFAULT NULL COMMENT 'represents the zero based index of the item from the original jdoc',
  `type` varchar(255) DEFAULT NULL,
  `contactName` varchar(255) DEFAULT NULL,
  `role` varchar(255) DEFAULT NULL,
  `emailAddress` varchar(255) DEFAULT NULL,
  `phoneNumber` varchar(255) DEFAULT NULL,
  `addressLine1` varchar(255) DEFAULT NULL,
  `addressLine2` varchar(255) DEFAULT NULL,
  `addressLine3` varchar(255) DEFAULT NULL,
  `localityName` varchar(255) DEFAULT NULL,
  `postcode` varchar(255) DEFAULT NULL,
  `stateTerritoryCode` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_EnterpriseEthernet` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `action` varchar(255) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `billingAccountId` varchar(255) DEFAULT NULL,
  `afterHoursAppointment` varchar(255) DEFAULT NULL,
  `inductionRequired` varchar(255) DEFAULT NULL,
  `securityClearance` varchar(255) DEFAULT NULL,
  `notes` varchar(255) DEFAULT NULL,
  `tradingName` varchar(255) DEFAULT NULL,
  `heritageSite` varchar(255) DEFAULT NULL,
  `term` varchar(255) DEFAULT NULL,
  `serviceRestorationSLA` varchar(255) DEFAULT NULL,
  `accessAvailabilityTarget` varchar(255) DEFAULT NULL,
  `zone` varchar(255) DEFAULT NULL,
  `productType` varchar(255) DEFAULT NULL,
  `templateId` varchar(255) DEFAULT NULL,
  `templateVersion` varchar(255) DEFAULT NULL,
  `npdRequiredFlag` tinyint(4) DEFAULT NULL,
  `orderAcceptedFlag` tinyint(4) DEFAULT NULL,
  `designAssignCompletedFlag` tinyint(4) DEFAULT NULL,
  `csaId` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_ExportCommercialFinance` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Primary key for this table',
  `orderId` int(11) DEFAULT NULL COMMENT 'Order ID from the table Order',
  `account` varchar(255) DEFAULT NULL COMMENT 'Trading Name for the Order',
  `identifier` varchar(255) DEFAULT NULL COMMENT 'ROR ID or Deal Identifier',
  `samId` varchar(255) DEFAULT NULL COMMENT 'SAM ID for the Order',
  `state` varchar(255) DEFAULT NULL COMMENT 'State for the Order ID',
  `productType` varchar(255) DEFAULT NULL COMMENT 'Product Type whether EE or NS',
  `orderChannel` varchar(255) DEFAULT NULL COMMENT 'Order Channel whether Single site or Deal Based',
  `financeCode` varchar(255) DEFAULT NULL COMMENT 'Finance Code for the Order ID',
  `processId` int(255) DEFAULT NULL COMMENT 'Process ID from the instance',
  `createdBy` varchar(255) DEFAULT NULL COMMENT 'Process Initiator',
  `createdOn` datetime DEFAULT NULL COMMENT 'Created On',
  PRIMARY KEY (`id`),
  KEY `om_cmn_stg_exportcommercialfinance_identifier` (`orderId`),
  KEY `om_cmn_stg_exportcommercialfinance_producttype` (`productType`),
  KEY `om_cmn_stg_exportcommercialfinance_orderchannel` (`orderChannel`),
  KEY `om_cmn_stg_exportcommercialfinance_processid` (`processId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Table holds the data to export which will be populate by SP';

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_jdoc` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `recordTypeRefId` int(11) NOT NULL,
  `entityId` int(11) NOT NULL,
  `jdoc` json DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='utility table for parsing jdocs';

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_json` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `json` json DEFAULT NULL,
  `opo` json DEFAULT NULL,
  `contactId` int(11) NOT NULL,
  `designAssign` json DEFAULT NULL,
  `mpoNotification` json DEFAULT NULL,
  `iPactConfigure` json DEFAULT NULL,
  `col1` varchar(255) DEFAULT NULL,
  `col2` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_Milestone` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `aycaId` varchar(55) DEFAULT NULL COMMENT 'AYCA ID, maps to Order ID in Appian',
  `activityId` varchar(55) DEFAULT NULL COMMENT 'A key that identifies the activity in P6 uniquely',
  `activityName` varchar(255) DEFAULT NULL COMMENT 'Name to uniquely identify the activity',
  `SIMProjectManagerUsername` varchar(55) DEFAULT NULL COMMENT 'When appended the value ''@nbn.com.au'', this gives an email address who will form a part of stakeholders that are intended to receive notifications on actualised/delayed milestones on order',
  `SIMProjectManagerName` varchar(55) DEFAULT NULL COMMENT 'Formatted Username of the above mentioned SIM Project Manager Username',
  `baselineStartDate` varchar(55) DEFAULT NULL COMMENT 'baselineStart date for the activity',
  `baselineFinishDate` varchar(55) DEFAULT NULL COMMENT 'baselineFinish date of the activity',
  `startDate` varchar(55) DEFAULT NULL COMMENT 'activity start date',
  `finishDate` varchar(55) DEFAULT NULL COMMENT 'activity finish date',
  `actualStartDate` varchar(55) DEFAULT NULL COMMENT 'actualStart date of the activity',
  `actualFinishDate` varchar(55) DEFAULT NULL COMMENT 'activity actualFinish date',
  `actualised` varchar(55) DEFAULT NULL COMMENT 'Represents whether or not the Milestone is actualised.',
  `lastModifiedDate` varchar(55) DEFAULT NULL COMMENT 'lastModifiedDate',
  `lastModifiedBy` varchar(55) DEFAULT NULL COMMENT 'Holds the username that has modified the activity in P6 at last',
  `LastModified ByName` varchar(55) DEFAULT NULL COMMENT 'Formatted Username of the above mentioned updated by user',
  `orderId` int(11) DEFAULT NULL COMMENT 'Contains the Order ID if it is present if the AYCA is in Order Table',
  `errorFlag` tinyint(1) DEFAULT '0' COMMENT 'Flag to identify records which failed validations',
  `errorMessage` varchar(1050) DEFAULT '0' COMMENT 'to hold the validation error messages',
  `processId` int(11) DEFAULT NULL COMMENT 'processId to manage ',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Staging Table to hold the data parsed from the Milestone Import document';

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_MilestonesNotification` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `p6ProjectId` varchar(255) DEFAULT NULL,
  `appianId` varchar(255) DEFAULT NULL,
  `projectNumber` varchar(255) DEFAULT NULL,
  `locId` varchar(255) DEFAULT NULL,
  `siteAddress` varchar(255) DEFAULT NULL,
  `region` varchar(11) DEFAULT NULL,
  `deliveryPartner` varchar(55) DEFAULT NULL,
  `activityId` varchar(55) DEFAULT NULL,
  `activityName` varchar(255) DEFAULT NULL,
  `baselineStartDate` date DEFAULT NULL,
  `baselineFinishDate` date DEFAULT NULL,
  `forecastStartDate` date DEFAULT NULL,
  `forecastFinishDate` date DEFAULT NULL,
  `simProjectManagerName` varchar(55) DEFAULT NULL,
  `simProjectManager` varchar(55) DEFAULT NULL,
  `lastModifiedDate` date DEFAULT NULL,
  `lastModifiedBy` varchar(55) DEFAULT NULL,
  `expiredFlag` tinyint(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_NBNSelect` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `itemId` int(11) NOT NULL,
  `action` varchar(255) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `afterHoursSiteVisit` varchar(255) DEFAULT NULL,
  `inductionRequired` varchar(255) DEFAULT NULL,
  `securityRequirements` varchar(255) DEFAULT NULL,
  `billingAccountID` varchar(255) DEFAULT NULL,
  `notes` varchar(1000) DEFAULT NULL,
  `additionalNotes` varchar(1000) DEFAULT NULL,
  `tradingName` varchar(255) DEFAULT NULL,
  `heritageSite` varchar(255) DEFAULT NULL,
  `siteName` varchar(255) DEFAULT NULL,
  `ownerAwareOfProposal` varchar(255) DEFAULT NULL,
  `siteAccessInstructions` varchar(255) DEFAULT NULL,
  `siteType` varchar(255) DEFAULT NULL,
  `resourceOrderType` varchar(255) DEFAULT NULL,
  `propertyOwnershipStatus` varchar(255) DEFAULT NULL,
  `keysRequired` varchar(255) DEFAULT NULL,
  `contractedLocationInstructions` varchar(255) DEFAULT NULL,
  `orderAcceptedFlag` tinyint(4) DEFAULT NULL,
  `safetyHazards` varchar(255) DEFAULT NULL,
  `jsasswmRequired` varchar(255) DEFAULT NULL,
  `workPracticesRequired` varchar(255) DEFAULT NULL,
  `workingAtHeightsConsideration` varchar(255) DEFAULT NULL,
  `confinedSpaceRequirements` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_NTD` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx` int(11) DEFAULT NULL,
  `type` varchar(255) DEFAULT NULL,
  `batteryBackupRequired` varchar(255) DEFAULT NULL,
  `action` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdby` varchar(255) DEFAULT NULL,
  `createdondtime` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_Order` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `processId` int(11) NOT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `correlationId` varchar(255) DEFAULT NULL,
  `correlationName` varchar(255) DEFAULT NULL,
  `appianFolderId` int(11) DEFAULT NULL,
  `statusId` int(11) DEFAULT NULL,
  `substatusId` int(11) DEFAULT NULL,
  `locationId` int(11) DEFAULT NULL,
  `orderTypeRefId` int(11) NOT NULL,
  `state` varchar(255) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `orderDate` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expectedCompletionDate` datetime DEFAULT NULL,
  `completionDate` datetime DEFAULT NULL,
  `requestedStartDate` datetime DEFAULT NULL,
  `requestedCompletionDate` datetime DEFAULT NULL,
  `updatedBy` varchar(255) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `productHeaderId` int(11) DEFAULT NULL,
  `priId` varchar(255) DEFAULT NULL,
  `orderType` varchar(255) DEFAULT NULL,
  `applicationId` int(11) DEFAULT NULL,
  `accessSeekerContactId` int(11) DEFAULT NULL,
  `accessSeekerId` varchar(255) DEFAULT NULL,
  `pendFlag` tinyint(1) DEFAULT NULL,
  `opoAppianDocId` int(11) DEFAULT NULL,
  `npdStatusId` int(11) DEFAULT NULL,
  `npdSubstatusId` int(11) DEFAULT NULL,
  `sendNotificationsFlag` tinyint(1) DEFAULT NULL,
  `finalStatusCompletedFlag` tinyint(1) DEFAULT NULL,
  `parentOrderId` int(11) DEFAULT NULL,
  `subprocessPendFlag` tinyint(1) DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `opo` json DEFAULT NULL COMMENT 'stores the original product order json body note that this is not in the Appian CDT as we only use this in a stored proc and Appian doesn''t support the JSON data type.',
  `statusVersionId` int(11) DEFAULT NULL,
  `shortfallType` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_OrderItem` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `entityId` int(11) NOT NULL,
  `processId` int(11) NOT NULL,
  `orderId` int(11) DEFAULT NULL,
  `idx` int(11) NOT NULL COMMENT 'temp index given when inserting from json for each itemtype',
  `itemTypeRefId` int(11) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  `locationId` int(11) DEFAULT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `parentOrderItemId` int(11) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `mainLineItemFlag` tinyint(1) NOT NULL,
  `action` varchar(255) DEFAULT NULL,
  `state` varchar(255) DEFAULT NULL,
  `priority` int(11) DEFAULT NULL,
  `completionDate` datetime DEFAULT NULL,
  `expectedCompletionDate` datetime DEFAULT NULL,
  `requestedCompletionDate` datetime DEFAULT NULL,
  `requestedStartDate` datetime DEFAULT NULL,
  `createdOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime DEFAULT CURRENT_TIMESTAMP,
  `hideSummaryRowFlag` tinyint(1) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_OVC` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `action` varchar(255) DEFAULT NULL COMMENT 'will ultimately be saved against the OrderItem',
  `poi` varchar(255) DEFAULT NULL,
  `nni` varchar(255) DEFAULT NULL,
  `routeType` varchar(255) DEFAULT NULL,
  `sVLanId` varchar(255) DEFAULT NULL,
  `maximumFrameSize` varchar(255) DEFAULT NULL,
  `cosHighBandwidth` varchar(255) DEFAULT NULL,
  `cosMediumBandwidth` varchar(255) DEFAULT NULL,
  `cosLowBandwidth` varchar(255) DEFAULT NULL,
  `uniVLanId` varchar(255) DEFAULT NULL,
  `connectedTo` varchar(255) DEFAULT NULL,
  `enniLagId` varchar(255) DEFAULT NULL,
  `ovcTransientId` varchar(255) DEFAULT NULL,
  `cncId` int(11) DEFAULT NULL,
  `cosMappingMode` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `orderItemId` int(11) DEFAULT NULL,
  `samInstanceId` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_SFC` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `processId` int(11) DEFAULT NULL,
  `correlationId` varchar(255) DEFAULT NULL,
  `sfStatus` varchar(255) DEFAULT NULL,
  `sfQuoteName` varchar(255) DEFAULT NULL,
  `sfQuoteId` varchar(255) DEFAULT NULL,
  `sfParentOppName` varchar(255) DEFAULT NULL,
  `sfParentOppId` varchar(255) DEFAULT NULL,
  `sfOppName` varchar(255) DEFAULT NULL,
  `fibreBuildCategory` varchar(255) DEFAULT NULL,
  `locId` varchar(255) DEFAULT NULL,
  `latitude` varchar(255) DEFAULT NULL,
  `longitude` varchar(255) DEFAULT NULL,
  `fibreJointTypeCode` varchar(255) DEFAULT NULL,
  `fibreJointStatus` varchar(255) DEFAULT NULL,
  `fibreJointLatLong` varchar(255) DEFAULT NULL,
  `fibreJointId` varchar(255) DEFAULT NULL,
  `basketId` varchar(255) DEFAULT NULL,
  `address` varchar(255) DEFAULT NULL,
  `actualDistance` decimal(13,2) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_Site` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx1` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `idx2` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `cncName` varchar(255) DEFAULT NULL,
  `hostName` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_Tunnel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx1` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `idx2` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `idx3` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `hostName` varchar(255) DEFAULT NULL,
  `toHostName` varchar(255) DEFAULT NULL,
  `pathId` int(11) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `cncName` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_STG_UNI` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `idx1` int(11) DEFAULT NULL COMMENT ' represents the zero based index of the item from the original jdoc',
  `idx2` int(11) DEFAULT NULL COMMENT 'represents the zero based index of the item from the original jdoc',
  `action` varchar(255) DEFAULT NULL COMMENT 'will ultimately be saved against the OrderItem',
  `interfaceBandwidth` varchar(255) DEFAULT NULL,
  `portId` varchar(255) DEFAULT NULL,
  `interfaceType` varchar(255) DEFAULT NULL,
  `ovcType` varchar(255) DEFAULT NULL,
  `tpId` varchar(255) DEFAULT NULL,
  `transientId` varchar(255) DEFAULT NULL,
  `processId` int(11) DEFAULT NULL,
  `createdOnDTime` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `omId` varchar(255) DEFAULT NULL,
  `orderItemId` int(11) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_Tunnel` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `siteId` int(11) NOT NULL,
  `toHostName` varchar(255) DEFAULT NULL,
  `pathId` int(11) DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` timestamp NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `om_cmn_site_om_cmn_tunnel_fk` (`siteId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE IF NOT EXISTS `OM_CMN_UNI` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `btdId` int(11) NOT NULL,
  `itemId` int(11) NOT NULL,
  `recordTypeRefId` int(11) NOT NULL,
  `interfaceBandwidth` varchar(255) DEFAULT NULL,
  `portId` varchar(255) DEFAULT NULL,
  `interfaceType` varchar(255) DEFAULT NULL,
  `ovcType` varchar(255) DEFAULT NULL,
  `tpId` varchar(255) DEFAULT NULL,
  `transientId` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `createdBy` varchar(255) DEFAULT NULL,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  `orderId` int(11) DEFAULT NULL,
  `itemSubTypeRefId` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `om_cmn_uni_om_cmn_itemsubtyperefid_fk` (`itemSubTypeRefId`),
  KEY `om_cmn_btd_om_cmn_uni_fk` (`btdId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 1906  EE
CREATE TABLE IF NOT EXISTS `OM_CMN_R_ReasonCodeRef` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `code` varchar(255) DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL COMMENT 'describes reasoncode',
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

  CREATE TABLE IF NOT EXISTS `OM_CMN_PendHold` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `orderId` int(11) DEFAULT NULL,
  `reasonCodeRefId` int(11) DEFAULT NULL,
  `pendHoldDTime` datetime DEFAULT NULL,
  `createdBy` varchar(255) DEFAULT NULL,
  `createdOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatedOnDTime` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `updatedBy` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- 1906 NPD
